services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_ORIGIN=http://localhost:3000
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - QDRANT_HOST=qdrant
    depends_on:
      - qdrant
    volumes:
      - ./:/app
    restart: always
    command: ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  qdrant_data:
